blueprint:
  name: Badkamer Licht – Aanwezigheid & Tijd (Simpel)
  description: >
    Badkamerlicht dat bij binnenkomst langzaam aangaat volgens tijdschema.
    Tijdens aanwezigheid mag de gebruiker altijd handmatig dimmen.
    Na verlaten gaat het licht uit en bij volgende binnenkomst volgt
    weer het tijdschema.
  domain: automation

  input:
    presence_sensor:
      name: Aanwezigheidsmelder
      selector:
        entity:
          domain: binary_sensor

    light_target:
      name: Badkamerlamp (dimmer)
      selector:
        entity:
          domain: light

    light_off_delay:
      name: Licht uit na (minuten)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

    fade_in_seconds:
      name: Fade-in tijd (seconden)
      default: 3
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: sec

    day_start:
      name: Start dag
      default: "07:00:00"
      selector:
        time:

    evening_start:
      name: Start avond
      default: "18:00:00"
      selector:
        time:

    night_start:
      name: Start nacht
      default: "23:00:00"
      selector:
        time:

    brightness_day:
      name: Helderheid dag (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100

    brightness_evening:
      name: Helderheid avond (%)
      default: 60
      selector:
        number:
          min: 1
          max: 100

    brightness_night:
      name: Helderheid nacht (%)
      default: 15
      selector:
        number:
          min: 1
          max: 50

mode: restart

trigger:
  - id: presence_on
    platform: state
    entity_id: !input presence_sensor
    to: "on"

  - id: presence_off
    platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      minutes: !input light_off_delay

action:
  - choose:

      # ===== LICHT AAN BIJ BINNENKOMST =====
      - conditions:
          - condition: trigger
            id: presence_on
        sequence:
          - choose:

              # 🌙 NACHT
              - conditions:
                  - condition: time
                    after: !input night_start
                    before: !input day_start
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_night
                      transition: !input fade_in_seconds

              # ☀️ DAG
              - conditions:
                  - condition: time
                    after: !input day_start
                    before: !input evening_start
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_day
                      transition: !input fade_in_seconds

              # 🌆 AVOND
              - conditions:
                  - condition: time
                    after: !input evening_start
                    before: !input night_start
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_evening
                      transition: !input fade_in_seconds

      # ===== LICHT UIT BIJ VERLATEN =====
      - conditions:
          - condition: trigger
            id: presence_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_target
