blueprint:
  name: Badkamer Ventilatie – Slimme Naloop
  description: >
    Badkamerventilatie op basis van aanwezigheid.
    Korte aanwezigheid = korte naloop (wc).
    Lange aanwezigheid = lange naloop (douche).
  domain: automation

  input:
    presence_sensor:
      name: Aanwezigheidsmelder
      selector:
        entity:
          domain: binary_sensor

    fan_switch:
      name: Ventilatie (schakelaar)
      selector:
        entity:
          domain: switch

    presence_started:
      name: Helper – aanwezigheid gestart
      selector:
        entity:
          domain: input_datetime

    start_delay:
      name: Ventilatie start na (minuten)
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: min

    short_stay:
      name: Grens kort/lang verblijf (minuten)
      default: 7
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min

    run_after_short:
      name: Nalooptijd kort verblijf (minuten)
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min

    run_after_long:
      name: Nalooptijd lang verblijf (minuten)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: min

mode: restart

variables:
  presence_started_entity: !input presence_started
  short_stay_minutes: !input short_stay

trigger:
  - id: presence_on
    platform: state
    entity_id: !input presence_sensor
    to: "on"

  - id: presence_off
    platform: state
    entity_id: !input presence_sensor
    to: "off"

action:
  - choose:

      # ===== BIJ BINNENKOMST =====
      - conditions:
          - condition: trigger
            id: presence_on
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input presence_started
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

          - delay:
              minutes: !input start_delay

          - condition: state
            entity_id: !input presence_sensor
            state: "on"

          - service: switch.turn_on
            target:
              entity_id: !input fan_switch

      # ===== BIJ VERLATEN =====
      - conditions:
          - condition: trigger
            id: presence_off
        sequence:
          - variables:
              stay_minutes: >
                {{ (as_timestamp(now()) -
                    as_timestamp(states(presence_started_entity))) / 60 }}

          - choose:
              # KORT VERBLIJF
              - conditions:
                  - condition: template
                    value_template: "{{ stay_minutes < short_stay_minutes }}"
                sequence:
                  - delay:
                      minutes: !input run_after_short

              # LANG VERBLIJF
              - conditions:
                  - condition: template
                    value_template: "{{ stay_minutes >= short_stay_minutes }}"
                sequence:
                  - delay:
                      minutes: !input run_after_long

          - service: switch.turn_off
            target:
              entity_id: !input fan_switch
